const oracledb = require('oracledb');
require('dotenv').config();

async function run() {
  let connection;
  try {
    const connectString = `(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=${process.env.ORACLE_HOST})(PORT=${process.env.ORACLE_PORT}))(CONNECT_DATA=(SID=${process.env.ORACLE_SID})))`;
    connection = await oracledb.getConnection({
      user: process.env.ORACLE_USER,
      password: process.env.ORACLE_PASSWORD,
      connectString: connectString
    });
    
    console.log("Connected to Oracle.");

    const createTableSql = `
      CREATE TABLE ONT_SIR_BOT.INSERCION_AUDIT (
          AUDIT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          PLANILLA_ID VARCHAR2(50) NOT NULL,
          ACCION VARCHAR2(20) NOT NULL,
          USUARIO VARCHAR2(50) NOT NULL,
          EXPEDIENTE NUMBER,
          LOTE_ID NUMBER,
          MONTO_TOTAL NUMBER(15,2),
          FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
          DETALLES VARCHAR2(1000)
      )
    `;
    
    await connection.execute(createTableSql);
    console.log("Table INSERCION_AUDIT created successfully.");
  } catch (err) {
    if (err.message.includes('ORA-00955')) {
      console.log("Table already exists!");
    } else {
      console.error(err);
    }
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}
run();
