version: '3.8'
services:
  api-obtencion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-obtencion
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
